# Generated by Django 4.1.5 on 2023-01-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortdesc', models.TextField(max_length=64, verbose_name='Theme description')),
                ('amount', models.IntegerField(verbose_name='Themes amount')),
                ('template', models.ManyToManyField(related_name='themes', to='template.template', verbose_name='Theme')),
            ],
            options={
                'verbose_name': 'theme',
                'verbose_name_plural': 'themes',
            },
        ),
    ]
