# Generated by Django 4.1.5 on 2023-01-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='desc_af',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_ar',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_ar_dz',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_ast',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_az',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_be',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_bg',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_bn',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_br',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_bs',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_ca',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_cs',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_cy',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_da',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_de',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_dsb',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_el',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_en',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_en_au',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_en_gb',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_eo',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_es',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_es_ar',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_es_co',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_es_mx',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_es_ni',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_es_ve',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_et',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_eu',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_fa',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_fi',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_fr',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_fy',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_ga',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_gd',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_gl',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_he',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_hi',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_hr',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_hsb',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_hu',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_hy',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_ia',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_ig',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_ind',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_io',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_is',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_it',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_ja',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_ka',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_kab',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_kk',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_km',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_kn',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_ko',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_ky',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_lb',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_lt',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_lv',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_mk',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_ml',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_mn',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_mr',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_ms',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_my',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_nb',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_ne',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_nl',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_nn',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_os',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_pa',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_pl',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_pt',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_pt_br',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_ro',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_ru',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_sk',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_sl',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_sq',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_sr',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_sr_latn',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_sv',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_sw',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_ta',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_te',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_tg',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_th',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_tk',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_tr',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_tt',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_udm',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_uk',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_ur',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_uz',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_vi',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_zh_hans',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='desc_zh_hant',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_af',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_ar',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_ar_dz',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_ast',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_az',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_be',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_bg',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_bn',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_br',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_bs',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_ca',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_cs',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_cy',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_da',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_de',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_dsb',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_el',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_en_au',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_en_gb',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_eo',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_es',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_es_ar',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_es_co',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_es_mx',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_es_ni',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_es_ve',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_et',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_eu',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_fa',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_fi',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_fy',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_ga',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_gd',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_gl',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_he',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_hi',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_hr',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_hsb',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_hu',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_ia',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_ig',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_ind',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_io',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_is',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_it',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_ja',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_ka',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_kab',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_kk',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_km',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_kn',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_ko',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_ky',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_lb',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_lt',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_lv',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_mk',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_ml',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_mn',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_mr',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_ms',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_my',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_nb',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_ne',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_nl',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_nn',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_os',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_pa',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_pl',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_pt',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_pt_br',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_ro',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_sk',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_sl',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_sq',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_sr',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_sr_latn',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_sv',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_sw',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_ta',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_te',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_tg',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_th',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_tk',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_tr',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_tt',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_udm',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_ur',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_vi',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_zh_hans',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_zh_hant',
            field=models.CharField(max_length=50, null=True, verbose_name='Template name'),
        ),
    ]
