# Generated by Django 4.1.5 on 2023-01-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('introduction', models.TextField(max_length=255, verbose_name='Introduction')),
                ('questions', models.TextField(max_length=64, verbose_name='Question')),
                ('ending', models.TextField(max_length=255, verbose_name='Ending')),
            ],
            options={
                'verbose_name': 'MyProject',
                'verbose_name_plural': 'MyProjects',
            },
        ),
    ]
