# Generated by Django 4.1.5 on 2023-01-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
        ('project_id', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='theme',
            field=models.ManyToManyField(related_name='project_id', to='themes.theme', verbose_name='Project theme'),
        ),
    ]
