# Generated by Django 4.1.5 on 2023-01-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_id', '0001_initial'),
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64, verbose_name='Name')),
                ('created_date', models.DateField(verbose_name='Created')),
                ('updated_date', models.DateTimeField(verbose_name='Updated')),
                ('project_id', models.ManyToManyField(related_name='Project', to='project_id.myproject', verbose_name='Projects')),
                ('themes', models.ManyToManyField(related_name='Project', to='themes.theme', verbose_name='Themes')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
    ]
