# Generated by Django 4.1.5 on 2023-01-22 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='themes',
        ),
        migrations.AddField(
            model_name='project',
            name='themes',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='Themes'),
            preserve_default=False,
        ),
    ]
